[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink

; Pakai baris tunggal ini saja untuk bypass ID chip clone
upload_flags = -c set CPUTAPID 0x2ba01477

monitor_speed = 115200